### ISSUE TITLE
duplicate message

### ISSUE THREAD

**Issue by brunokcampos** [MassiveCraft/CreativeGates#112]
whenever I install massive core it doubles my chat or rather he buga .
![sem titulo](https://cloud.githubusercontent.com/assets/14867436/10130400/b4651090-659e-11e5-9c67-4f9a429fedf1.png)

**Comment by ulumulu1510** [comment]
I am quite sure that the issue is not caused by us, but a chat plugin which is acting weird.

Try this:
- Start a clean testserver with just MassiveCore and Creativegates and see if the issue persists.
- if there is no issue, start adding your other plugins one by  one and see which one is causeing the issue.

If you then come back and can provide proof that our plugin is missbehaving, please provide the version number of MassiveCore aswell as the server version alongside with a stacktrace/console log of your problem. Till you do this testing, @brunokcampos, we cannot help you further

**Comment by oloflarsson** [comment]
You are using HeroChat. Edit the /mstore/massivecore_conf/instance.json and set "usingRecipientChatEvent" to false.
