### ISSUE TITLE
CreativeGates wont load/work

### ISSUE THREAD

**Issue by wesley27** [MassiveCraft/CreativeGates#117]
Hello again, sorry to bother you if this is another simple issue, but I don't think the problem you described is the problem in my case. This was my error: http://pastebin.com/0ES282e3

I didn't update only creative gates, I updated both MassiveCore and CreativeGates from BukkitDev yesterday, as I updated every single plugin on my server. I'm running the MassiveCore 1.9 beta and the CreativeGates 1.9 beta.

**Comment by ulumulu1510** [comment]
From your stacktrace, you are not running the 1.9 Beta 2.8.7, as the versionnumber stated is 2.8.6.
"Enabling CreativeGates v2.8.6".

Please delete both MassiveCore and CreativeGates and replace them with the coppies you get when unzipping the bundle you get from spigot: https://www.spigotmc.org/resources/massivecore.1901/

You can write on closed issues, if the issue actually still persists. But this error only happens when you use mismatched versions of our software.
